##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # client
  client:
    image: ${IMAGE_CONSUL}
    container_name: "client.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "client.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/client/conf:/etc/consul/conf:ro
      - ./volume/client/data:/tmp/consul/data:rw
      - ./volume/client/logs:/tmp/consul/logs:rw
    command: agent -config-dir=/etc/consul/conf
    ports:
      - "8300:8300/tcp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8500:8500/tcp"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    networks:
      mynet:
        ipv4_address: 172.16.110.20
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.110.0/24"
